import type {Metadata} from "next";
import "./index.css";
import {ThemeProvider} from "@/components/ThemeProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <head/>
        <body>
        <ThemeProvider
            attribute="class"
            defaultTheme="black"
            enableSystem
            disableTransitionOnChange
        >
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
